### ISSUE TITLE
urls to user profile pages are accessible without login

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#100]
Without logging into a session on the gis hub, I can see profile pages for users:

For example: https://www.gis-hub.ca/user/neec_reader

I don't see this as a major issue, but should it be accessible? @genkimaps do you see this as a bug/problem?

**Comment by genkimaps** [comment]
It's not a major issue, since I think you can't click through to there from the homepage without being logged in.  This is a legacy of CKAN being designed to be open by default. There is no single switch you can flip to make a CKAN site totally private.  User info is probably also visible through the API. You can add this to the list but it should be fairly low priority.

**Comment by cole-fields** [comment]
Agreed - my only concern was the list of datasets that the user has created listed on their profile page. but, as you mentioned, it's not possible to further navigate using any of those links/information. will close this
