### ISSUE TITLE
Add hubupload service to supervisor

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#112]
Hubupload service is currently running as a system-level service but in theory we should keep system services separate from application services.

`/home/dfo/hub-geo-api/conf` contains hubupload.conf and .service files. 

Disable and put service under supervisor.

**Comment by genkimaps** [comment]
A Few things have to be done for this:

1. disable existing hubupload service. The service definition file is here: https://github.com/genkimaps/hub-geo-api/blob/master/conf/hubupload.service.  Command to disable: `sudo systemctl disable hubupload`. Also stop the service: `sudo systemctl stop hubupload`.
2. Run the gunicorn command from the hubupload service conf by itself, make sure it works. We need to add options `--user` and `--group` for the socket permissions. Group has to be `www-data` to allow nginx to connect to the unix socket. We also have to run the command as `sudo`.  Also have to add some options at the top, specific to supervisor. We do NOT want to run as `user=dfo` because dfo is not root and does not have permission to set the group for the socket file to `www-data`. 
3. `sudo /home/dfo/.virtualenvs/hubapi/bin/gunicorn --workers=3 --threads=10 --user dfo --group www-data --bind unix:hubupload.sock -m 007 wsgi:app`.  Ensure that the upload detector works as normal when this is running. 
4. Add this line to supervisor conf. Then remove the existing supervisor conf: `sudo rm /etc/supervisor/conf.d/tk.conf`
5. Symlink the new conf file from this repo: `sudo ln -s /home/dfo/hub-geo-api/conf/supervisor.conf /etc/supervisor/conf.d/gishub.supervisor.conf`
6. Reload supervisor config: `sudo supervisorctl reload` and then `sudo supervisorctl status`.  Sometimes supervisor chokes on this, doesn't shut down completely, and you have to kill it: `ps -ef | grep supervisord` and then kill the process that supervisor is running under. Then `sudo kill -s SIGTERM <process id>`
7. Supervisor should have four services: ckan, hubupload, jobs, solr.  
8. Logs for hubupload are now under supervisor: `sudo tail -f hubupload-stderr---supervisor-*.log`

**Comment by genkimaps** [comment]
@cole-fields  Update on this: I have now created a separate supervisor config file, only for the hubupload process.  See this commit: https://github.com/genkimaps/hub-geo-api/commit/54ae1a44e4d0cac21c33d2e2d2d95130fb986213

Additional documentation: https://github.com/genkimaps/hub-geo-api#running-hub-geo-api-as-a-service-in-supervisor

**Comment by cole-fields** [comment]
@genkimaps, looks good. I can see hubupload listed under supervisor now. Is the `-m 007` mainly a security setting to allow file permissions for the group `www-data` to the .sock file and restrict permissions for other groups/users?

**Comment by genkimaps** [comment]
@cole-fields The `-m 007` flag sets this file permission:

```
cd ~/hub-geo-api
ll *.sock
srwxrwx---   1 dfo www-data    0 Jul 18 23:23 hubupload.sock=
```

Ignore the leading s for now. `007` is a file umask that corresponds to the permissions triplet `rwxrwx---` See: https://en.wikipedia.org/wiki/Umask.  It means that user dfo (the owner of the file) and the www-data group (which nginx runs under) both have full permissions on the socket file, meaning: read, write, and execute.  The `---` at the end means all other users (not dfo, and not in the www-data group) are completely denied access to the file.
