### ISSUE TITLE
Contact DFO cloud services

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#127]
While the system is operating well where it is (AWS, outside of DFO network), there are some benefits to having it within the DFO system. 

- [x] Confirm if AWS is a possibility under DFO cloud environment. Last we checked, they only supported MS Azure. 
- [x] Contact Rob Skelly about his experience with trying to deploy some services through DFO Cloud services for the database project.
- [x] If they only support Azure, confirm w/Joanne that we do indeed want to proceed with moving the system under DFO cloud. This would require significant time/effort. 
- [ ] Unclear if we did move to DFO cloud services if the system is then only accessible behind the DFO network. This would disrupt a couple services (go-kit download tool, development from outside the DFO network?).
- [x] Complete price estimate for services using https://azure.microsoft.com/en-us/pricing/calculator/. 
- [x] Complete Simple Cloud Services Request Form .
- [x] Send form to cloud team.
- [ ] Wait for them to assess and they will send a SoS (Statement of Sensitivity) form to complete. Fill and return once received.

**Comment by cole-fields** [comment]
### What are all the services we use?

| Service | Purpose | Category |
| :------------- | :----------: | :----------: |
| EC2 |  | Compute |
| S3 |  | Storage |
| EFS |  | Storage |
| Route 53 |  | Networking & Content Delivery |
| Cloudwatch |  | Management & Governance |
| Simple Notification System (SNS) |  | Application Integration |
| IAM |  | Security, Identity, & Compliance |
| AWS Billing |  | Billing |

**Comment by genkimaps** [comment]
@cole-fields 
I think this list is complete. In addition to the external services, there are the usual internal services within the OS (such as cron jobs) that need to be set up.  Regarding the domain: if you use an Azure service that is hosted inside the DFO network, you almost certainly won't need a domain name. It will be some internal server address.  Check whether the DFO network supports SSL internally.  Some services require SSL by default, and might need some unusual configuration to make them work on a private (non-SSL) network. 

This all assumes that you can actually get root access to a server on the DFO Azure network. My previous discussions with someone at DFO was basically "they don't give you the keys to the system anymore" which is why we ended up going with an external server in the first place. However, maybe that has changed since I left DFO.

**Comment by cole-fields** [comment]
So the DFO cloud services team does not allow anyone outside of IMTS to use the virtual machines to develop/host web applications. They do offer VMs and storage, but the VMs are only to be used for data analyses. Unfortunately, this means we are still in the same position of not being able to move behind the DFO firewall. Only IMTS would be permitted to build/maintain the system as far as I understand. 

@genkimaps no need to worry about or look into Azure for now. I had spent some time on it, thinking that we would be able to migrate, but it turns out that the answer is still no.
