### ISSUE TITLE
Support email notifications for dataset changes

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#49]
Support email notifications and trigger subscribe/unsubscribe when a dataset is added/removed from user’s favorites.  The default email notification for a user’s favorites should be:  notify when any resource in the dataset has been updated.  Event tracking should include download events.

**Comment by cole-fields** [comment]
low priority because users can use the dashboard feature

**Comment by cole-fields** [comment]
1. edit cron jobs
`export VISUAL=vim; crontab -e`
`@hourly /home/tk/venv/bin/paster --plugin=ckan post -c /home/tk/ckan/dfo.ini /api/action/send_email_notifications > /dev/null`
* set to hourly as a test, but should change to weekly

2. edit config file to enable email notifications
`ckan.activity_streams_email_notifications = True`


3. restart ckan
`sudo supervisorctl restart ckan`

4. this option should probably be set to 7 days otherwise it will not include stuff older than 2 days once this is changed to a weekly job
`#ckan.email_notifications_since = 2 days`

**Comment by cole-fields** [comment]
@genkimaps just a heads up that i was trying to troubleshoot this today and will take another look tomorrow. I didn't get an email notification as expected after the steps above and wanted to confirm it was working using hourly before switching it to weekly.

**Comment by cole-fields** [comment]
testing this:
switch user and add cron job
`su tk`
`export VISUAL=vim; crontab -e`
`@hourly echo '{}' | /home/tk/venv/bin/paster --plugin=ckan post -c /home/tk/ckan/dfo.ini /api/action/send_email_notifications > /dev/null`

`sudo supervisorctl restart ckan`
`sudo supervisorctl restart jobs`

**Comment by genkimaps** [comment]
@cole-fields Hi Cole, back at my desk now after a few days.  This is on the list for tomorrow.

**Comment by genkimaps** [comment]
@cole-fields  A couple of things to note, and sorry if I did not mention this in the wiki.  When running a paster command, you have to switch to user `tk` for the duration of the command.  This is because in at least one of the extensions, it writes to a log file that is owned by tk.  So the command should be: 

`sudo -u tk /home/tk/venv/bin/paster --plugin=ckan post -c /home/tk/ckan/dfo.ini /api/action/send_email_notifications` 

However, this still does not work, because it tries to access the API for sending email notifications using this URL:  `http://localhost/api/action/send_email_notifications`.  The internal web service for CKAN and its API are running on an internal socket at port 3031, which is defined in the supervisor conf file at `/home/tk/supervisor.conf`.  It looks like this is hardcoded somewhere to use `localhost` instead of the site URL.  The only reference to `localhost` in the CKAN conf file is for the Postgresql database connection. 

A **much simpler solution** is to avoid using `paster` entirely and simply add a curl command (or a bash shell script containing the curl command) to the cron job.

**Comment by genkimaps** [comment]
@cole-fields Before setting up the cron job, there are a couple of things that should probably be undone.  

1. "adding port 587 in the ini file for the smtp server" where did you make this change? We are using mailgun to send all of our emails, so having port 587 open on our server is irrelevant. 
2. You made some changes to one of the cron files.  Be careful with this.  Ideally we should put all of the cron jobs in one file.  I can't remember which cron file I used for the most popular datasets script, but we should put it in the same place as that and make sure it's documented clearly.

**Comment by genkimaps** [comment]
@cole-fields I went ahead and added a daily cron job for this. See the last line in /home/dfo/dfo-crontab.  For some reason, I am not getting email updated for datasets that I'm following, even though I have notifications enabled in my user page.

**Comment by cole-fields** [comment]
@genkimaps Thanks for looking into this - seems to be working now as I received a few emails overnight about notifications. The reason you may not get the notifications is that another user would have to make some changes to some object (dataset, organization, group) you were following rather than changing it yourself. I made a dummy account for testing this when I was troubleshooting. I will take a look at the updated ini file and the wiki entry for cron tabs. Do you think weekly or daily emails is more appropriate?

1. I deleted this after the testing didn't work. It was `smtp.server = smtp.mailgun.org:587` which I changed back to `smtp.server = smtp.mailgun.org` in the ini file.

2. I did create a cron file `/home/tk/hourly.cron` which I deleted after testing. There is also a `/home/tk/daily` which I did not create and can maybe be deleted? The paster commands I added to the dfo-crontab file were deleted after I tested as well so I think I cleaned everything up.

**Comment by genkimaps** [comment]
@cole-fields This file: `/home/tk/tk.daily.cron` contained only one entry, which was a duplicate of the first line in the DFO cron file at `/home/dfo/dfo-crontab`, the one that runs the command `--plugin=ckan tracking update`.  Since it's a duplicate, I removed that command from the tk account cron file.  This keeps things consistent: all cron jobs that are related to CKAN are in `/home/dfo/dfo-crontab`.

**Comment by genkimaps** [comment]
@cole-fields 

> Do you think weekly or daily emails is more appropriate?

My opinion, weekly is better.  People will get annoyed with daily updates.

**Comment by cole-fields** [comment]
@genkimaps agreed - I changed this to a weekly job in the cron file `/home/dfo/dfo-crontab`
