### ISSUE TITLE
enable hyperlinks in 'Scripts or Software Routines' metadata field

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#62]
currently, the URLs do not hyperlink to the webpage. low priority as users can copy/paste the URL. doable?

**Comment by genkimaps** [comment]
This should be doable if we change the Scripts or Software Routines field to type Markdown.

**Comment by genkimaps** [comment]
@cole-fields 
I took a quick look at this, since I thought it would be low-hanging fruit. Was able to change the field type to `markdown.html` in our schema file. When editing a dataset, it shows the markdown syntax, which is fine. However, the _display_ does not reflect this. In other words, the _form snippet_ correctly shows the Markdown link with a popup showing example markdown syntax, but there does not appear to be a corresponding _display template_ for rendering the markdown on the dataset page.  This seems like a rather major oversight...  Will step away from this for now, since it's low priority.

**Comment by genkimaps** [comment]
Looks like there is a template helper function `{{ h.render_markdown(g.site_about) }}` but it has to be manually added to a display template.

**Comment by cole-fields** [comment]
This is great! Can you enable markdown support for the following fields (I know it's a lot, but will be useful/cleaner)

- Summary
- Temporal Coverage
- Methods
- Spatial Data Quality
- Positional Accuracy
- Attribute Accuracy
- Logical Consistency
- Uncertainties
- Email (Data Creator and Program Manager)
- Data Sources
- Change history (don't worry about this one if it isn't simple)

**Comment by genkimaps** [comment]
@cole-fields Everything is done except:
- Change history. need to check possible complications on this. 
- Email.  Do you simply want the email address to be clickable and open with the user's default email program?  Otherwise I don't see the need for full markdown formatting, since this field should only contain an email address.

**Comment by cole-fields** [comment]
@genkimaps great, this looks good. re email: true, just a clickable email address is sufficient. and the change history field - this one is pretty low priority so no need to spend much time on it

**Comment by genkimaps** [comment]
@cole-fields Clickable email is done.
