### ISSUE TITLE
enable page tracking view

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#70]
I'd like to enable this feature: https://docs.ckan.org/en/2.8/maintaining/tracking.html
it looks pretty useful. Also very easy to change according to the instructions so I wouldn't mind giving this a shot. on the wiki page, it says that the dfo.ini config file is on the git repo, but i wasn't able to find it. that file is what is by default called production.ini from CKAN, correct? I made a branch for this, and can edit the file, but unsure about adding it to the repo as it doesnt seem to be there now. this can wait until we do a demo of your work envi. I copied the file to my local machine with scp 
I'm away tomorrow, but will be back on Tuesday (training on Monday)

**Comment by genkimaps** [comment]
> it says that the dfo.ini config file is on the git repo, but i wasn't able to find it. 

I was planning to put that file in git, but I decided not to do so for a couple of reasons. Will explain later. 

> that file is what is by default called production.ini from CKAN, correct?

Correct.  If you need to edit the file, you can do so using `nano` from the command line, or copy it with `scp` to your local PC. 

I can enable this setting and test it out. Will get to this later today.

**Comment by genkimaps** [comment]
@cole-fields  If you want to know in detail why I do not want to put the CKAN ini file in git, read this: https://github.com/genkimaps/gis-hub/issues/67#issuecomment-596399579

@cole-fields I enabled this tracking feature.  When viewing a dataset through the API, such as https://www.gis-hub.ca/api/3/action/package_show?id=rcas, the "tracking_summary" field does not show up. This might be because we are using a custom schema for our datasets. However, sorting datasets by Popular does work.  The instructions for this says that you have to update the tracking data by running a cron job. The command to update tracking is:

`/home/tk/ckan`
`sudo -u tk /home/tk/venv/bin/paster tracking update yyyy-mm-dd -c dfo.ini`
where the date is the start date from which you would like to begin aggregating page views. 

There are two tables in the database with the tracking data:
tracking_summary
tracking_raw
Page views are stored immediately in tracking_raw, but it looks like you have to run the tracking update command to get any new info in the tracking_summary table. That's a very odd way of doing it; in my opinion, tracking_summary should be an aggregate view of data in the tracking_raw table. 

I'll set up a cron job to run once per day for this.

**Comment by cole-fields** [comment]
> Correct. If you need to edit the file, you can do so using `nano` from the command line, or copy it with `scp` to your local PC.
Sounds good - I didn't want to directly edit on the server it in case it was on the git repo

**Comment by cole-fields** [comment]
> @cole-fields I enabled this tracking feature. When viewing a dataset through the API, such as https://www.gis-hub.ca/api/3/action/package_show?id=rcas, the "tracking_summary" field does not show up. This might be because we are using a custom schema for our datasets. However, sorting datasets by Popular does work. 

I think you're likely correct about the API call not returning the tracking information because of the custom extensions. That's ok. I'm hoping that the 'Highlighting Popular Datasets and Resources' will work once there is enough activity. Thanks for implementing this. With the cron job set up to run daily, the running_total count in the tracking_summary table should increment. It that's true, then I think the highlighting popular datasets should work. This is excellent.

**Comment by cole-fields** [comment]
@genkimaps i was looking in the tracking_summary table and it doesn't look like it's been updated. I know you mentioned setting up a cron job to have the raw tracking data put in to the summary table... anyways I wanted to manually update it as a test. 
So I activated the virtual env and navigated to the ckan directory where the config file is. Next, ran 
`sudo paster tracking update --config=./dfo.ini`

This threw the error ImportError: No module named sqlalchemy

Just wondering if we need to install a package. I guess in this case, it's a python module, not a linux package.

**Comment by genkimaps** [comment]
@cole-fields 
You need to run the paster command without sudo.  Steps should be:
1. activate venv: `source /home/tk/venv/bin/activate`
2. change location:  `cd /home/tk/ckan`
3. `paster tracking update -c /home/tk/ckan/dfo.ini`

Might also have to do this: 

`sudo chmod a+w /home/tk/ckanext-dfo/ckanext/dfo/logs/dfoext.log` since the log file might get recreated with only root having write permissions.

**Comment by genkimaps** [comment]
@cole-fields Looking at the entries in tracking_summary and tracking_raw tables, the script to generate tracking statistics appears to go through _every possible URL_, including the ones for different languages.  We have many entries like https://www.gis-hub.ca/sk/revision/af746757-6e2e-4b6a-ac0e-42b120879f10 which is a valid URL but not needed.  

Issue to disable the other languages is here: https://github.com/genkimaps/gis-hub/issues/71

**Comment by genkimaps** [comment]
@cole-fields The cron job was not created correctly.  Need to do this
`crontab -e`

At end of this file, add this line: 

`@daily /home/tk/venv/bin/paster --plugin=ckan tracking update -c /home/tk/ckan/dfo.ini && /home/tk/venv/bin/paster --plugin=ckan search-index rebuild -r -c /home/tk/ckan/dfo.ini`

Save it in /home/dfo/dfo-crontab

Then install to system crontab:

`crontab /home/dfo/dfo-crontab`

Ensure that it worked:

`sudo cat /var/spool/cron/crontabs/dfo`

**Comment by genkimaps** [comment]
This cron job:
`/home/tk/venv/bin/paster --plugin=ckan tracking update -c /home/tk/ckan/dfo.ini`
Has not been running daily.  I can verify this by looking for entries in the tracking_summary table in postgres, which have not been updated since March 25 (that was the last day that I ran it manually).  When I try to manually run the above command, I get this error:

`IOError: [Errno 13] Permission denied: '/home/tk/ckanext-dfo/ckanext/dfo/logs/dfoext.log'` 

Permissions error on the log file for the ckanext-dfo extension.  This log file gets re-created every day with permissions `-rw-r--r-- 1 tk tk`, so it's only accessible to user tk.  Likely solution: put this in the cron job for user tk.  

This cron job is now installed for user tk. Confirm tomorrow that it ran.

**Comment by genkimaps** [comment]
@cole-fields  I deleted all the junk entries (dead links for languages we are not using) in `tracking_raw`and re-generated stats in `tracking_summary`.  The sort by Popular is giving the expected results, most heavily accessed at the top.

**Comment by cole-fields** [comment]
@genkimaps ok great thanks, i did notice that the sort by popular was working after looking at the tracking tables in the database.

**Comment by genkimaps** [comment]
@cole-fields New page tracking summary data is now being generated every night.  Closing this issue.

**Comment by cole-fields** [comment]
@genkimaps is it possible to revisit to see if the tracking summary data can easily be included in the metadata retrieved from api calls like https://www.gis-hub.ca/api/3/action/package_show?id=seamounts

Mainly, I think it would be cool and useful if popular datasets were highlighted (https://docs.ckan.org/en/2.8/maintaining/tracking.html) which as you mentioned may be because of our custom metadata schema. If this is a very complicated enhancement, then don't worry about it

**Comment by genkimaps** [comment]
@cole-fields Are you talking about the "on fire" icon as shown here: https://docs.ckan.org/en/2.8/maintaining/tracking.html#highlighting-popular-datasets-and-resources?  I'm not sure why that isn't working on our site. The tracking table is being refreshed and sorting datasets by Popular is working.  

I don't think adding tracking data to the package_show API would be easy.  This is a core API in CKAN and I'm not sure if it's designed to be extendable.

**Comment by cole-fields** [comment]
@genkimaps yes, that's the feature I was hoping to include by adding the tracking extension. Ok, no worries, just thought it would be an interesting addition. You mentioned in an earlier comment that package_show is not retrieving/showing the tracking summary (possibly) because of our custom schema. However, once `ckan.tracking_enabled = true` I think the extension is meant to include the tracking_summary data in the api call.

**Comment by cole-fields** [comment]
@genkimaps  just an FYI

modified method described here: https://github.com/ckan/ckan/issues/4972

changed banner: True in /home/tk/ckan/ckan/templates/snippets/package_grid.html package_list.html package_item.html

modified /home/tk/ckan/ckan/templates/snippets/package_item.html line 44 to reduce min threshold from 10 to 8

now the popular badge is showing when i'm on that branch on the server:

![image](https://user-images.githubusercontent.com/52669482/95255139-c89b9500-07d5-11eb-94ac-aab52c90a140.png)

**Comment by genkimaps** [comment]
Nice work! Thanks for tracking that down.

**Comment by cole-fields** [comment]
@genkimaps reopening this as tracking does not seem to be updating... low priority and I can take a look at it some time. looking at the tracking summary table in the ckan database shows that the most recent tracking date is 10/6/2020 from what i can tell.

**Comment by cole-fields** [comment]
@genkimaps I think this issue is resolved now. the tracking table was not being updated, don't think the cron job was running. I'll check tomorrow to see if it updates, but after running manually, the tracking_summary table was updated.

0. looked at tracking_summary table in postgres database - not updated since 10/6/2020
![tracking1](https://user-images.githubusercontent.com/52669482/112388688-c3ad9d80-8cb0-11eb-8337-1bc79cbbd8bb.PNG)

1. checked cron jobs in `/home/tk/tk.daily.cron` - confirmed it was empty
2. copied command `/home/tk/venv/bin/paster --plugin=ckan tracking update -c /home/tk/ckan/dfo.ini` to `/home/tk/tk.daily.cron` file
3. switched to user tk, and ran command manually (no permission error as with user dfo)
4. checked tracking_summary table

![tracking2](https://user-images.githubusercontent.com/52669482/112388723-cf995f80-8cb0-11eb-945d-c84362fe4ab7.PNG)

**Comment by genkimaps** [comment]
@cole-fields Just to follow up, I double checked this and seems to be working fine.  tracking_summary is being updated nightly
