### ISSUE TITLE
Security Review

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#75]
@cole-fields 
- how did the oliviersabourin account get created? According to Joanne, he said that he sent an email and was registered. Is this a backdoor we are unaware of? Web registration has been disabled for a long time. Maybe we can simply ask him. 
- review email logs for the above
- review existing users.  Pending users: send them a reminder to activate their account within a certain time, if they don't do it, delete. 
- enable session timeout in CKAN config file
- consider geo blocking IP addresses outside BC
- update robots.txt to disable all indexing. 
- is there a way to remove existing content indexed by google?   https://bit.ly/2Rncxza 
- delete all other admin accounts. See list here. what is account 'default'? https://www.gis-hub.ca/ckan-admin 
- consider putting the server behind a VPN in Amazon: https://aws.amazon.com/vpc/.  This would require all clients to have a VPN client installed on their PC, but it would be extremely secure, and the site would be completely removed from the public internet. However it would add some admin overhead and cost.

**Comment by genkimaps** [comment]
- how did the oliviersabourin account get created? in table public.user:
         name          |  state  |          created           |             email              
oliviersabourin       | deleted | 2019-07-08 06:50:25.725048 | Olivier.Sabourin@dfo-mpo.gc.ca
By July 2019, we definitely had web registration disabled.  He got in some other way.  Did he get an invitation from another user?  Unfortunately no record of this in the logs.  CKAN by default does not log these events. 

- review email logs for the above
Email logs not available on the server, everything was sent through mailgun, and the mailgun account is still using Tyler's settings.  I could update ckan core to add logging to the email notifications module. 

- enable session timeout in CKAN config file. 
This is done in dfo.ini:
`who.timeout = 3600`

- update robots.txt to disable all indexing. 
This is done, now contains disallow all command. 

- is there a way to remove existing content indexed by google? 
Yes, but it requires registering the property with Google Search console. Not worth the trouble.  The pages that are currently indexed in Google are different language versions of the landing page, e.g. https://www.gis-hub.ca/de. Nothing else was crawled by google because it's behind a password wall.  These other language pages are now all returning a 404 error, which is what we want. See this for reference: 
https://support.google.com/webmasters/answer/9689846?hl=en&visit_id=637220297538202290-3375571475&rd=1

- consider geo blocking IP addresses outside BC
https://www.howtoforge.com/nginx-how-to-block-visitors-by-country-with-the-geoip-module-debian-ubuntu
Looks like in theory, blocking or allowing cities or regions is also possible:
https://kb.isc.org/docs/aa-01149
But let's consider whether we really want to do this.

**Comment by cole-fields** [comment]
@genkimaps nothing happened that should make us worry about security of the site. I think there's some confusion. He requested an account (emailed me) following a presentation from Joanne sometime last year. I checked that he was DFO and registered an account for him thinking he was interested in the site. 

Probably what Joanne said was that in his report about the GIS Hub, Olivier claimed that you can just email to get an account/register. He was implying that there's no checks in place when registering users, but what more can you do but look them up and verify their email address and that they're a DFO employee? But yes, I created the account for him which Joanne knows. I don't think we have reason to be worried about a backdoor or anything like that. I've since removed his account at Joanne's request. 

The status is: CHS national didn't want Pacific CHS data on the GIS Hub and they were removed. Olivier made a report about the GIS Hub with some misinformation. Pacific CHS and others are in the process of getting support to get the CHS data back on the hub.

**Comment by genkimaps** [comment]
@cole-fields LOL ok, that explains everything. I thought we had a hidden backdoor somewhere. And that the site turning green might have been a calling card.  

I still think it would be a good idea for you to review all active and pending users.  We should probably do that periodically.  FYI, I deleted users tktech and default.

**Comment by genkimaps** [comment]
Increased timeout in CKAN config file to 48 hours:
`who.timeout = 172800`
