### ISSUE TITLE
Fix Request Access button

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#79]
On the site, I've made some datasets public and restricted download access for the resource to users who are members of the dataset owner's organization. For example: https://www.gis-hub.ca/group/environmental-layers are public (metadata viewable to all users) but download access restricted to members of MSEA. 

![image](https://user-images.githubusercontent.com/52669482/82846904-ef4cd500-9e9f-11ea-8d44-d1a7e1a3519f.png)

However, the problem i've encountered when testing is the Request Access button fails for users who do not have download permissions. 

![image](https://user-images.githubusercontent.com/52669482/82846919-fffd4b00-9e9f-11ea-856a-95176e1211c1.png)

**Comment by genkimaps** [comment]
@cole-fields  I think this is now fixed. Luckily it was not too hard to track down.  There is a really dumb line of code in ckanext-restricted: 

https://github.com/genkimaps/ckanext-restricted/blob/c28b105c5ef7029df2b7d87071c0d86bc7f82ed4/ckanext/restricted/controller.py#L89

It tries to read the property `email_to` from the CKAN config file (which is any email address for errors and admin messages), and if not available, it uses `email_to_undefined` instead.  Later, the mailer tries to send an email to _both_ the dataset maintainer and the `email_to` email address, and blows up because "email_to_undefined" is not a valid email address.  

The solution was to add `email_to` (my gmail) in the config file.  Never encountered this before, so I didn't realize we had to fill in that field in the conf file.  I tested again and it works. 

However, a secondary issue came up in the Mailgun logs, entirely unrelated from this one. When sending the email to your DFO address, the log says: "Failed, 4.3.2 Please try again later"  This 4.3.2 is a SMTP reply from the DFO email server: either it was down at the time of this test, or it's grey/blacklisting these emails.  I don't think mailgun is at fault; they do a very good job of ensuring deliverability, unless the target mail server is badly configured (which would not surprise me, knowing DFO IT). 

Please keep this in mind, in case your users report that they have not received emails that they were expecting (registration emails, requests for data). 

The data request message was delivered to my gmail with no problems.  I will forward it to you.

**Comment by genkimaps** [comment]
Also, the name on the email is "None" but that's of lesser importance.

**Comment by cole-fields** [comment]
Great - glad it was a quick fix. This is useful since now we can properly have public metadata while keeping the resource download private to members of the same organization. Nice work.

Thanks for letting me know about the second issue with my DFO email. I'll keep that in mind. I think regardless, if a user wants access and the button fails or they don't hear from me, they'll likely get in touch directly with me or Joanne or Kayleigh for access.

**Comment by genkimaps** [comment]
@cole-fields Is this working now? Seems to be fine. If so, you can close it

**Comment by cole-fields** [comment]
> @cole-fields Is this working now? Seems to be fine. If so, you can close it

Yes, this is working as expected and have had users request access to datasets. Closing now.
