### ISSUE TITLE
Add view for web-page-view plugin

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#84]
Try to use API to add a view for this plugin: https://docs.ckan.org/en/ckan-2.7.3/maintaining/data-viewer.html#web-page-view

There is a chance this could be done with the ckanapi and the resource_create_default_resource_views() action.

**Comment by genkimaps** [comment]
More info:

Would be good to include this on the back end as you mention Michael, or if that doesn’t work, it could be part of the publishing process. For the title of the new webpage view for each resource, I just take the last part of the web map preview URL. For example, the 100 m substrate web map preview link is https://maps.gis-hub.ca/raster/substrate100m_data_rfsubstrate_100m and the title of the embedded preview is substrate100m_data_rfsubstrate_100m.

**Comment by cole-fields** [comment]
@genkimaps this is not fully automated, but I modified this function a while ago: https://github.com/genkimaps/hub-geo-api/blob/9aa9e6c99d534b673a6b4abddb5cc5dfa67ba063/hubutils.py#L965 to generate web map views for each resource in a dataset if they don't exist (or all if a dataset is not specified). For me, I think this is sufficient since I can just run this for datasets that do not have the map/webpage view at the resource level.
