### ISSUE TITLE
reorder resources button does not save/commit changes

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#87]
@genkimaps 

from a dataset's edit page, a user should be able to reorder the resources. on the front end, this looks like it works (users can move/reorder resources). however, after saving and refreshing, this does not actually have an effect. 

https://docs.ckan.org/en/ckan-2.7.3/api/#ckan.logic.action.update.package_resource_reorder

package_resource_reorder function in `/home/tk/ckan/ckan/logic/action/update.py`

could use the patch resources function, but if it's an option on the front-end, should be functional.

**Comment by genkimaps** [comment]
@cole-fields  Do you know if this ever worked on our site?  I seem to recall that when Tyler made the custom dataset views, this functionality may have been broken.

**Comment by cole-fields** [comment]
@genkimaps I don't remember it ever working, so you may be correct. It's a low priority issue but it's come up a couple times. I guess the confusing part is for users, the functionality looks like it's available, but the changes are not actually saved/committed. 

Overall, there are more important tasks, but this could be a backburner item. I will perhaps look into using the resource patch function here as well.

**Comment by cole-fields** [comment]
@genkimaps i think since I have a script to do this, i'll close it. maybe I will note it in the docs that users can request resources to be reordered alphabetically if desired. it does make the resources look cleaner and is the default but sometimes gets rearranged if datasets are updated

**Comment by genkimaps** [comment]
@cole-fields 
Reopening this because I found the root cause, and we really should have this basic functionality working.  The cause is that the resource reordering screen uses jQuery to get a list of the resources with HTML class `resource-item`.  However in the ckanext-dfo extension, we override this class name with `resource-item-dfo`.  See this template:  https://github.com/genkimaps/gis-hub/blob/e79fbf070d99a1756b5f00140512ed8f9e435008/ckanext/dfo/templates/package/snippets/resource_item.html#L7

Try to figure out why this was done (e.g. for CSS), and was it really necessary?  Can't we just use the resource-item class?

**Comment by genkimaps** [comment]
Class `resource-item` only appears once in core CKAN, in the template resource_item.html.  In the DFO extension, `resource-item-dfo` class is used only in the same place in the same file.  `resource-item-dfo` never appears in the CSS, instead I used a nested class inside this, `resource-item-dfo-preview` which in retrospect was an excellent idea.  We should be able to fix this just by changing back to `resource-item` class.

**Comment by genkimaps** [comment]
This is now working, but required some fiddly changes to the css to make spacing and styles match what we had before.

**Comment by genkimaps** [comment]
@cole-fields  I verified that resource entries created by hub-geo-api after uploading a file are in alphabetical order. 

https://github.com/genkimaps/hub-geo-api/blob/4126ca620eaecfcfef2cebf2d18b7f58b3136713/geoparser.py#L491

**Comment by cole-fields** [comment]
@genkimaps thanks for tracking that down.

Option 1: if we modify so that the download placeholder position cannot be changed (always at the top), i'm fine with having the resource reorder feature enabled. 

Option 2: if you estimate it will take more than ~half a day for option 1, then I think just disabling the functionality is the best option.

**Comment by genkimaps** [comment]
@cole-fields 
I managed to do option 1.  The existing resource reorder interface has been left unchanged.  However, if users put the download placeholder anywhere other than the first position, then as part of dataset validation on the server, the download resource will be bumped back to first position immediately.  Since this is invisible to users, I think it's important to mention this in the documentation (so that it doesn't look like a bug).  

This is done in branch `restore_changehist`

**Comment by cole-fields** [comment]
@genkimaps This is excellent! tested it out today and works perfectly, nice work. Glad you were able to implement that (i know it might have been tedious to have the placeholder remain in the top position). I'll try and take a look at the code soon - this week and the next are fairly meeting heavy unfortunately.
