### ISSUE TITLE
Add button to generate HNAP XML file

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#91]
This issue is complementary to this one in the hub-geo-api backend script: https://github.com/genkimaps/hub-geo-api/issues/25

There is already a script in hub-geo-api to generate the XML file.  Here are the relevant factors / components:
- hub-geo-api uses Python 3, CKAN uses Python 2.  We would have to trigger this from the command line, rather than using Python bindings directly.  Not ideal.  Alternatively, could move the code from hub-geo-api to this repo and backport to Python2 where needed. 
- Add a button element on user interface
- Add a custom action for this button.  Need to check that the the script to generate XML was triggered, get a return code from that script, ensure that XML file exists
- Send XML file to browser as a download file.  Need something like python-Flask's `return send_file(zipped, as_attachment=True)` but I'm not sure if that Flask component is available in CKAN.  

@cole-fields This feature is more complicated to implement than you might think.

**Comment by cole-fields** [comment]
Thanks for outlining the steps that would be required for this. I looked into a bit, but didn't know the specifics (things like sending the XML file to browser). 

Is the dataset and resource metadata accessible as part of the spatial processing pipeline? What if after that process completes, generating the xml file is triggered as part of that workflow and stored on the mapserver with a link? Then maybe we could add a link to the resource metadata page? I guess it would also have to be triggered if only the dataset metadata were updated too though. Otherwise, the xml file might be dated if the parent metadata is modified. I haven't fully thought that out, but just brainstorming...

**Comment by genkimaps** [comment]
@cole-fields  Looking at the code for generating HNAP, I see you have calls to google translator with a built-in delay.  How long does it take to generate an output file?  If it's longer than the typical webserver timeout (about 60 seconds) then the button to download the HNAP file might not work.  Otherwise, it should be possible.  I have other code in CKAN that interacts with hub-geo-api via a call to the system command line.

**Comment by cole-fields** [comment]
@genkimaps it takes about 5-10 seconds to run, and the built-in delay could be reduced. 

When running it, you'll likely encounter this error which is from the googletrans module. 

`2020-11-23 10:08:59,840:INFO:fileutils(395) - Loaded 7941 species codes.`
`2020-11-23 10:09:00,397:INFO:ckanapi(29) - API key loaded ok.`
`'NoneType' object has no attribute 'group'`

Related issue: https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group

The problem is inconsistent though and will work if i change nothing, but run it multiple times. I've used a more recent version of the google translator module and the fork/branch noted in the stackoverflow discussion with the same results. So, something to improve on for sure.

**Comment by genkimaps** [comment]
@cole-fields  We have now switched to using the Amazon AWS translator in the hub-geo-api code, so I went ahead and tried hooking up the hnap exporter to the CKAN frontend.  Encountered a number of weird issues along the way, which I will try to document completely.  More on this later.  The change was made in this branch: https://github.com/genkimaps/gis-hub/tree/contact_autocomp

I was thinking of renaming the branch, since we're no longer trying to do autocomplete in the contact fields, but it's already referenced in too many places.

**Comment by genkimaps** [comment]
@cole-fields  Here are the challenges I encountered with this ticket.  I realize that just adding a button to download a file doesn't sound complicated, but there are a lot of other things going on behind the scenes. 

1. First, I updated the hnap export code in hub-geo-api to use a default export location, if the output folder is not provided as a parameter to the script.  The default is `/home/dfo/hub-geo-api/metadata_archive/hnap_metadata`

2. hub-geo-api runs on Python 3.x, and CKAN on Python 2.x, so they don't talk to each other natively, at least not easily.  The way to make them talk is to use a `subprocess` call from CKAN to run the hnap script from the Linux command line.  To make this work, the user has to be changed to dfo, in order to get environment variables and so on (CKAN code runs under the tk user).  See this function: https://github.com/genkimaps/gis-hub/blob/1cf930fda94a45c5edf82b0d331773cb1e579ae4/ckanext/dfo/dfo_plugin_settings.py#L19

3. I added an API action in plugins.py, 'hnap_export'.  This can be used to generate the xml file, but because it runs within the CKAN API framework it can only return a JSON result, and it cannot respond with a file download to the browser.  To use this API endpoint, switch to the contact_autocomp branch, and try a url like https://www.gis-hub.ca/api/3/action/hnap_export?resource_id=b1a24c96-eaa6-4433-a706-99854894be13.  The "result" field contains the location of the HNAP xml.  

4. When I first tried to run this through the API, it caused CKAN to freeze completely.  This is because there are two concurrent HTTP requests at the same time, one for the hnap_export API call, and the other used internally by the hnap exporter to get metadata for the resource & dataset.  This caused it to freeze up because the uwsgi service that runs CKAN has been _single-threaded_, but it never caused a problem until now (because we never had two or more requests at the same time that both had to complete before the response could be returned).  The uwsgi service is defined in the `/home/tk/supervisor.conf` file.  I tried running it with multiple processes and threads, as suggested here: https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#adding-concurrency-and-monitoring, but for some reason this caused the CKAN database to lock up with concurrency errors.  Through trial and error, I found out that it works with a _single process and multiple threads._  The uwsgi line in supervisor.conf now looks like this: `command=uwsgi --paste config:/home/tk/ckan/dfo.ini --socket :3031 -H /home/tk/venv --threads 4`  and with 4 threads, this problem is solved.  supervisor.conf is not in git version control, so be sure that you make a copy of this file.  

5. I tried connecting the same hnap export function with a custom route defined in plugins.py:  https://github.com/genkimaps/gis-hub/blob/1cf930fda94a45c5edf82b0d331773cb1e579ae4/ckanext/dfo/plugins.py#L346, I thought we might be able to use flask's `send_file` function to send the xml as a file download.  This is how Flask normally works.  However this does not work in CKAN for some reason.  

6. The best I could do, which is an ugly hack, was to make the xml file available as a static file.  The problem is that this does not download the file, it merely displays the xml content in the browser:  https://www.gis-hub.ca/test05.xml.  To make this work, I also had to modify the ckan ini file to serve files from the HNAP export folder: https://docs.ckan.org/en/2.9/maintaining/configuration.html#extra-public-paths.  This is a security issue because any xml file in there can be accessed by a user who can guess the url pattern (which is not hard).  

By the way, the HNAP button on the resource page is temporarily disabled.   If I can't figure out how to make the xml file download the way we want, my suggestion is to instead have the hnap script in hub-geo-api send the xml file by email to the user who initiated the request.  This is more secure, requires less back and forth between different pieces of software, and does not cause a blocking HTTP request.  What do you think?

**Comment by cole-fields** [comment]
@genkimaps thanks for the detailed notes on this issue. You're right, there's a lot of underlying complexity that you wouldn't necessarily think about in order to produce and download a file. I think an email with the xml file attached is totally fine. That way we can even include some kind of disclaimer in the body of the email stating that the french translation needs to be validated and that there may be placeholder text in some fields. That keeps things fairly straightforward then, right? Is the button set up with text (i.e. 'Generate XML File') or is it an icon? Might be useful to have it say something like 'Email HNAP XML file' if possible. I think once the feature is implemented, we can add a description in the docs saying that users will receive an email with the file. I can just imagine someone clicking it expecting a file download, and then proceeding to click the button ten more times.

**Comment by genkimaps** [comment]
@cole-fields This seems to be working now, I am getting emails with the HNAP file attached.  We are still getting a few rate limiting errors from the Amazon translator. See logfile /home/dfo/hub-geo-api/metadata_archive/hnap-export.log

`botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the TranslateText operation (reached max retries: 4): Rate exceeded`

I'm a bit surprised that they are giving you a "rate exceeded" error when you are paying for the service.  You should look into what their rate limit is, and add a delay if necessary.

**Comment by cole-fields** [comment]
@genkimaps Excellent! This is great work, thanks for implementing it. I will take a look at the throttling exception error from Amazon translate sometime this week. I tested on a couple of resources and it was perfect.

**Comment by genkimaps** [comment]
@cole-fields  I merged the HNAP branch (contact_autocomp) with master, production server is now running master. Closing this issue.
